sonar.projectKey=dimsmaul_lunar-kit
sonar.organization=lunar-kit
sonar.sources=packages
sonar.exclusions=**/*.test.ts,**/*.spec.ts,node_modules/**
sonar.coverage.exclusions=**/*.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
