const noop = () => null;
export const useRouter = () => ({ push: () => {}, replace: () => {}, back: () => {}, pathname: '', params: {} });
export const useNavigation = () => ({ navigate: () => {}, goBack: () => {}, setOptions: () => {} });
export const usePathname = () => '';
export const useSearchParams = () => ({ get: () => null });
export const Link = noop;
export const Stack = { Screen: noop };
export const Tabs = { Screen: noop };
export const Redirect = noop;
export const router = { push: () => {}, replace: () => {}, back: () => {} };
export const Slot = noop;
export const ErrorBoundary = noop;
export const useGlobalSearchParams = () => ({});
export const useLocalSearchParams = () => ({});
export const useSegments = () => [];
export const useRootNavigationState = () => ({});
export const navigationContainerRef = { current: null };
export const createURL = () => '';
export const useFocusEffect = () => {};
export const ExpoRoot = noop;
export default {};
