// Stub for react-native-gesture-handler in web/docs context
export const GestureHandlerRootView = ({ children }: { children: React.ReactNode }) => children;
export const GestureDetector = ({ children }: { children: React.ReactNode }) => children;
export const Gesture = { Pan: () => ({}), Tap: () => ({}), Native: () => ({}) };
export const PanGestureHandler = ({ children }: { children: React.ReactNode }) => children;
export const TapGestureHandler = ({ children }: { children: React.ReactNode }) => children;
export const ScrollView = require('react-native-web').ScrollView;
export const FlatList = require('react-native-web').FlatList;
export const Switch = require('react-native-web').Switch;
export const TextInput = require('react-native-web').TextInput;
export const DrawerLayout = ({ children }: { children: React.ReactNode }) => children;
export const TouchableOpacity = require('react-native-web').TouchableOpacity;
export const TouchableHighlight = require('react-native-web').TouchableHighlight;
export const TouchableNativeFeedback = require('react-native-web').TouchableHighlight;
export const TouchableWithoutFeedback = require('react-native-web').TouchableWithoutFeedback;
export const RawButton = ({ children }: { children: React.ReactNode }) => children;
export const BaseButton = ({ children }: { children: React.ReactNode }) => children;
export const RectButton = ({ children }: { children: React.ReactNode }) => children;
export const BorderlessButton = ({ children }: { children: React.ReactNode }) => children;
export const LongPressGestureHandler = ({ children }: { children: React.ReactNode }) => children;
export const PinchGestureHandler = ({ children }: { children: React.ReactNode }) => children;
export const RotationGestureHandler = ({ children }: { children: React.ReactNode }) => children;
export const FlingGestureHandler = ({ children }: { children: React.ReactNode }) => children;
export const ForceTouchGestureHandler = ({ children }: { children: React.ReactNode }) => children;
export const NativeViewGestureHandler = ({ children }: { children: React.ReactNode }) => children;
export const Directions = {};
export const State = {};
export const gestureHandlerRootHOC = (Component: any) => Component;
export const createNativeWrapper = (Component: any) => Component;
export default {};
