const noop = () => null;
export const NavigationContainer = noop;
export const useNavigation = () => ({ navigate: () => {}, goBack: () => {}, setOptions: () => {} });
export const useRoute = () => ({ params: {} });
export const useFocusEffect = () => {};
export const useIsFocused = () => true;
export const useNavigationState = () => ({});
export const ParamListBase = {};
export const StackActions = { push: () => {}, pop: () => {}, replace: () => {} };
export const CommonActions = { navigate: () => {}, goBack: () => {}, reset: () => {} };
export const createNavigatorFactory = (nav: any) => nav;
export default {};
