// Stub for react-native-reanimated in web/docs context
import { Animated } from 'react-native';

export const useSharedValue = (init: any) => ({ value: init });
export const useAnimatedStyle = (fn: any) => ({});
export const withSpring = (value: any) => value;
export const withTiming = (value: any) => value;
export const withDelay = (_delay: any, anim: any) => anim;
export const withSequence = (...args: any[]) => args[args.length - 1];
export const withRepeat = (anim: any) => anim;
export const runOnJS = (fn: any) => fn;
export const runOnUI = (fn: any) => fn;
export const useAnimatedGestureHandler = () => ({});
export const useAnimatedScrollHandler = () => ({});
export const useAnimatedRef = () => ({ current: null });
export const scrollTo = () => {};
export const interpolate = (value: number, _input: number[], output: number[]) => output[0];
export const Extrapolation = { CLAMP: 'clamp', EXTEND: 'extend', IDENTITY: 'identity' };
export const Easing = { linear: (t: number) => t, ease: (t: number) => t, bezier: () => (t: number) => t };
export const cancelAnimation = () => {};
export const useAnimatedReaction = () => {};
export const useDerivedValue = (fn: any) => ({ value: fn() });
export const measure = () => null;
export const useFrameCallback = () => {};
export const createAnimatedComponent = (Component: any) => Component;
export const View = require('react-native-web').View;
export const Text = require('react-native-web').Text;
export const Image = require('react-native-web').Image;
export const ScrollView = require('react-native-web').ScrollView;
export const FlatList = require('react-native-web').FlatList;
export default { createAnimatedComponent, View, Text, Image, ScrollView, FlatList };
